baseURL = 'http://vile.github.io/'
languageCode = 'en-us'
title = 'Investigations by 0xFantasy'
theme = 'smol'

summaryLength = 20

[params]
title = 'Investigations by 0xFantasy'
description = 'Investigator & Security Researcher, Contributor Boring Security DAO, ex-BlowfishXYZ'
